name: Verify

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  go-vet-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64

      - name: Run tests
        run: go test -race -vet=off -json ./... > TestResults.json

      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-test-results
          path: TestResults.json